name: Build and Release

on: push

jobs:
  build-publish:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
        id: go

      - name: Build for Linux
        run: |
          go build ./yomitan

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: yomitan
          name: yomitan-import-macos
