name: Build and Release

on: push

jobs:
  build-publish:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
        id: go

      - name: Build for Linux
        run: |
          # Create build directory
          build_dir="yomitan-import-macos"
          mkdir -p "$build_dir"

          # Build
          go build -o "$build_dir" ./yomitan
          # go build -o "$build_dir" ./yomitan-gtk

          # Zip the build directory
          zip -r "$build_dir.zip" "$build_dir"

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: yomitan-import-macos.zip
          name: yomitan-import-macos
